### ISSUE TITLE
The commit message prefix does not take effect

### ISSUE THREAD

**Issue by misitebao** [devops-infra/action-commit-push#25]
## :memo:  Brief description

The `commit_prefix` option is set in the configuration, but it is not displayed in the generated commit message.

![image](https://user-images.githubusercontent.com/28185258/143508306-88a5411a-e8dc-439d-af58-881127236b1a.png)

![image](https://user-images.githubusercontent.com/28185258/143508277-df0483f5-751f-4867-8df6-268446bfead9.png)

## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [ ] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [x] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Hello. Thank you for reaching out.
This is in fact an expected behaviour since `commit_message` is evaluated before `commit_prefix`.
Here is a code handling that https://github.com/devops-infra/action-commit-push/blob/master/entrypoint.sh#L58
I'll add a small explanation to the readme file.

**Comment by misitebao** [comment]
@ChristophShyper 
Okay, I understand the cause of the problem, thank you!
