### ISSUE TITLE
Add git-lfs to docker action

### ISSUE THREAD

**Issue by ejlevin1** [devops-infra/action-commit-push#27]
## :memo:  Brief description
Currently the action-commit-push doesn't support repos that have git lfs enabled.  It would be great if the Dockerfile could also install git-lfs so that it won't fail on commits.

https://github.com/devops-infra/action-commit-push/blob/21398281c939ea77c66416756ee63001f51c0a13/Dockerfile#L54 could simply add [git-lfs](https://pkgs.alpinelinux.org/packages?name=git-lfs&branch=edge)

## :warning: Checklist
* [ X] Provided a clear and concise description of what the issue is.
* [ X] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [ X] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Hello. Good idea. I've added it in the newest version `v0.5`.
