### ISSUE TITLE
URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by vfdev-5** [devops-infra/action-commit-push#32]
## :memo:  Brief description

Thanks for the GHA !  I was trying to use to in my sandbox to commit and push changes to the repository.
I have the following issue:
```
fatal: unable to access 'https:///vfdev-5/github-actions-playground/': URL using bad/illegal format or missing URL
```
- https://github.com/vfdev-5/github-actions-playground/runs/5306489871

I was using the following configuration:

https://github.com/vfdev-5/github-actions-playground/blob/8f9e7f2d04d93438ad6e1c14da12bf11439cec31/.github/workflows/deploy-to-gh-pages.yml#L52-L60

Any hints on how to solve that ?
Thanks 

## :warning: Checklist
* [ ] Provided a clear and concise description of what the issue is.
* [ ] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [ ] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Thank you for noticing that. It should be now fixed in version `v0.7`.
