### ISSUE TITLE
'remote rejected' error while running example in README

### ISSUE THREAD

**Issue by damianooldoni** [devops-infra/action-commit-push#59]
## Brief description

Hi 👋 I am trying to run your first example in the documentation in my public repository, [damianooldoni/test-workflows](https://github.com/damianooldoni/test-workflows).

## Error message 

I get this error:

```
[INFO] Target branch: main
[INFO] Committing changes.
[main 7071c70] Replaced foo with bar
 1 file changed, 2 insertions(+), 2 deletions(-)
[INFO] Pushing changes
To https://github.com/damianooldoni/test-workflows
 ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/reprod-documentation-workflow.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/damianooldoni/test-workflows'
```

See more details in the action [run log](https://github.com/damianooldoni/test-workflows/runs/7070071593?check_suite_focus=true).

I have no idea why this basic example fails. Do you? 

## Notes

Notice that I used the combination of your actions action-commit-push and [action-pull-request](https://github.com/devops-infra/action-pull-request) in a workflow, [fetch-data](https://github.com/damianooldoni/test-workflows/blob/main/.github/workflows/fetch-data.yaml), without any problem.

Many thanks.

**Comment by ChristophShyper** [comment]
Hi. It's exactly what the error says:  
* refusing to allow a GitHub App to create or update workflow `...` without `workflows` permission

You need to go to your PAT permissions and assign it with:
![image](https://user-images.githubusercontent.com/45788587/176183917-9f5c064e-5b83-4f6c-8f6e-9c33b67ef44e.png)

**Comment by ChristophShyper** [comment]
I've tested it and seems like a general issue in GitHub. Giving your PAT `workflow` permissions and enabling `read/write` in repo settings doesn't solve it.

But maybe the question is, do you really need to update workflows automatically?
Maybe you can use variables instead of hardcoded values there?

**Comment by damianooldoni** [comment]
I don't need it, indeed. I just wanted to report a problem while running your example in the README. Maybe should you modify the example by changing something in another directory, e.g. the root directory?

**Comment by ChristophShyper** [comment]
Ah, sorry, somehow I missed that :)
Thank you, I've fixed that in README.md.
But still, it's strange it's not straightforward to update workflow files from Actions.
