### ISSUE TITLE
Actions - Add files and commit from the python script in the data folder in github

### ISSUE THREAD

**Issue by jairamjidgekar** [devops-infra/action-commit-push#65]
## :memo:  Brief description

Hi, 

I am trying to work on GitHub and python scripting.
Intention is to automate the python script execution in the GitHub using the actions. 

Python script perform the web scraping and the data is stored in csv file. Csv file should be placed in the same repository where the python script is being used. 

Can you please have a look at my repo (actions and .py file) and let me know what is wrong with the code?

https://github.com/jairamjidgekar/test_repo_file_placement.git

**Comment by jairamjidgekar** [comment]
Hey, Well that worked seamlessly. Thank you for that :)  

But what I am not clear is, using the below code = 

 - name: Run the Action
      uses: devops-infra/action-commit-push@master
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        commit_message: "Files placed"


It uses devops-infra. I need to use mine. I tried replacing my user name. but that didn't work. 
I haven't even create secret keys as well. So is it pulling the required keys from your repo?

**Comment by ChristophShyper** [comment]
Well. Seems like you don't know the basics of git (as a CLI tool) and Github Actions.
I would suggest reading some documentation on both.

` I need to use mine` - read about setting required credentials for git in Github Actions.
`So is it pulling the required keys(GITHUB_TOKEN) from your repo?` - No, it's your default token. It's just how Github Actions work.

**Comment by jairamjidgekar** [comment]
Hi, 
Yes. I will reread the documentation. 

Thanks for the help :)
