### ISSUE TITLE
Using this repo - https://github.com/devops-infra/action-commit-push for replacing tag in helm repoistory

### ISSUE THREAD

**Issue by zohebs341** [devops-infra/action-commit-push#83]
## :memo:  Brief description
In my Github Actions workflow, I've added the below code which will help in replacing tags(Helm Tag). The problem is, I am not able to create a secret with name GITHUB_TOKEN and even I've tried giving different names but still I am getting same error.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/62261716/227006100-e48507db-0e1f-4d05-8984-d97cca0f2ffa.png">
 

Code I am using in Github Actions Workflow:

     
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated

Expectation is, it will replace tag in my helm/values.yaml file. 

## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [x] Given a clear and concise description of what is expected.
* [x] Proposed a clear and concise description of any alternative solutions or other features.
* [ ] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by zohebs341** [comment]
@ChristophShyper Thanks for your response. Actually, I am the owner of this repository - https://github.com/zohebs341/flux-aks. (But it's a private repository)

Because the repository is Private, I am getting this error? Appreciate your help.

![image](https://user-images.githubusercontent.com/62261716/227188666-f65a4b80-bd50-4bc8-a864-120e4907bfe0.png)

**Comment by zohebk8s** [comment]
@ChristophShyper you are correct. I've added workflow permissions and it worked. I've tested the use-case in both Private and Public repo and it's working. Thank you for your response.

![image](https://user-images.githubusercontent.com/128701612/227207946-79dcbc2e-1981-4e3d-9272-c60fc3b1fd17.png)
